### ISSUE TITLE
Using this plugin

### ISSUE THREAD

**Issue by YotYot** [tzsk/filepond-plugin-zipper#1]
Hi,
I was referred to your plugin by Rik from Filepond, as I'm looking to compress folders before uploading - so it looks like you've developed it right on time for me :)

Could you share some example on how to use it?

Thanks!

**Comment by tzsk** [comment]
@YotYot Yes. I've plans to release this package this weekend as an NPM package. Do you think you can wait that long?

It is not yet published 😔

**Comment by YotYot** [comment]
Sure! I'll be the first user 👍

**Comment by tzsk** [comment]
@YotYot Hey [`v1.0.0`](https://github.com/tzsk/filepond-plugin-zipper/releases/tag/1.0.0) just released. Feel free to use it and let me know if you find any issues.
